### PR TITLE
Isra 214 fixed layout

### PR DESCRIPTION
**Pull request by israelperezglez**
- [x] Rounded images with mixin border-radius
- [x] Add icon GitHub in navbar and footer
- [x] Fixed border radius wizard
- [x] Spread the world: add modal with social media
- [x] Add button in books-docs section
- [x] Add breadcrumb for the library in the navbar
- [x] Delete numbers in the sidebar
- [x] Fixed hover in the sidebar
- [x] Fixed text line in the sidebar (2 lines)
- [x] Increase font-size in the exercises
- [x] Change background code block
- [x] Change sidebar z-index

### CODE REVIEW

**Comment by israelperezglez** [comment]
@raulraja @rafaparadela Can you please review? Thanks

**Comment by rafaparadela** [comment]
Should we solve this issue in other ticket @israelperezglez ?

**Comment by rafaparadela** [comment]
You marked `Add button in books-docs section` as done, however, they are not linkable so far.

**Comment by israelperezglez** [comment]
The issue is in the other ticket

**Comment by rafaparadela** [comment]
Besides two comments, changes look great to me! Good job dude. :+1:

**Comment by israelperezglez** [comment]
This button was created, is possible that was broken in a merge with @dialelo. I will review this section

**Comment by israelperezglez** [comment]
@rafaparadela I updated the commit  "Add button in books-docs section". Can you please review? Thanks

**Comment by raulraja** [comment]
Beside the TODO LGTM!

**Pull request merged**
