### PR TITLE
SKO-33 Fixing tests

### PR DESCRIPTION
**Pull request by rafaparadela**
This PR solves initial issues related to tests. It make work:

- Application unit test.
- Integration test
- Scala.js test with the framework uTest.

Ticket: http://47degrees.myjetbrains.com/youtrack/issue/SKO-33

@raulraja  Could you review please? Thank you.

### CODE REVIEW

**Comment by raulraja** [comment]
LGTM

**Comment by raulraja** [comment]
@rafaparadela Some of the stuff here may be now outdated, please take a look and merge once fixed.

**Comment by rafaparadela** [comment]
Yes! I was waiting your merging in order to avoid conflicts to you. After my merging I'll create a new issue to add CI.

**Comment by raulraja** [comment]
:+1:

**Pull request merged**
