### PR TITLE
Fixed layout - 231

### PR DESCRIPTION
**Pull request by israelperezglez**
- [x] Add different states in exercises
- [x] review font-size text
- [x] Review button states white exercises is compiling

### CODE REVIEW

**Comment by israelperezglez** [comment]
@dialelo Can you please review? Thanks

**Comment by dialelo** [comment]
Can we reformat the .scss files to have consistent indentation? I believe 4 spaces are used throughout the rest of the code.

**Comment by dialelo** [comment]
A couple of comments:

- [ ] Non-exercise `pre` blocks shouldn't have a minimum height
- [ ] We may want to disable the button completely instead of simply hiding it. 
- [ ] When evaluating the button is clickable and it shouldn't

Other than that LGTM, great stuff :+1:

**Comment by dialelo** [comment]
Outstanding work, LGTM :shipit:

**Pull request merged**
