### PR TITLE
Coerce only "true" and "false" strings to booleans

### LINKED ISSUE #137: Boolean coercion uses `false` as the default case and it shouldn't
When coercing user-submitted inputs to boolean (for example in the "Literal Booleans" exercise), strings that are converted to boolean will be `false` by default unless they are the text `"true"`. Coercing a string to a boolean should ensure that the input is either `"true"` or `"false"` and fail otherwise.

This means that the inputs that are expected to be `false` will be considered as good even when containing bogus strings that aren't `"true"`.

### PR DESCRIPTION
**Pull request by dialelo**
Closes #137

### CODE REVIEW

**Comment by dialelo** [comment]
Just rebased on top of `version-2`and this merges cleanly, @raulraja should we make any modifications here?

**Comment by raulraja** [comment]
This is great but it's a great example of something we can test with ScalaCheck for all strings not in that set. Let's add it if you also find it appropriate so there is some good examples of the types of tests that we expect in future contributions.

**Comment by dialelo** [comment]
Good point!

**Comment by dialelo** [comment]
@raulraja check it out please.

**Comment by raulraja** [comment]
LGTM! Would love to have @noelmarkham look at it in case he can suggest any improvements but this is great! 

LGTM

**Comment by noelmarkham** [comment]
LGTM - I like it :+1:

**Comment by dialelo** [comment]
\o/

**Pull request merged**
