### PR TITLE
Update maps.json

### PR DESCRIPTION
**Pull request by alien11689**

### CODE REVIEW

**Comment by rafaparadela** [comment]
@alien11689 Thank you for your contribution. I think that the way you've addressed the problem of accessing to not found key, is valid. But doesn't comply with the philosophy that each exercise is an assertion that must be met. What do you think @raulraja ?

The original exercise:
```
val myMap = Map("OH" -> "Ohio", "WI" -> "Wisconsin", "IA" -> "Iowa")

intercept[NoSuchElementException] {
  myMap("MI") should be()
}
```

The new proposal:
```
val myMap = Map("OH" -> "Ohio", "WI" -> "Wisconsin", "IA" -> "Iowa")
val aNewMap = myMap - "OH"

intercept[NoSuchElementException] {
  aNewMap(__)
}
```

**Comment by raulraja** [comment]
@rafaparadela @alien11689 I think this will prove this case better:

```scala
val myMap = Map("OH" -> "Ohio", "WI" -> "Wisconsin", "IA" -> "Iowa")
var blewWithException = true
intercept[NoSuchElementException] {
  myMap("MI")
  blewWithException = false
}
blewWithException should be(_)
```

`blewWithException` should remain `true` since `myMap("MI")` will raise the exception before `blewWithException` mutates.

**Comment by rafaparadela** [comment]
@raulraja This solution looks good to me.
@alien11689 Could you address this change in order to preserve your contribution, please? Thank you.

**Comment by alien11689** [comment]
Ok, I've fixed it.

**Comment by rafaparadela** [comment]
Cool. Thank you @alien11689

**Pull request merged**
