### PR TITLE
Abstract exercise discovery/parsing/compilation process

### PR DESCRIPTION
**Pull request by andyscott**
This encapsulated several things.. and is currently WIP. Additional I will need to rebase this as other PRs are completed.

- [x] refactor exercise service to support multiple methods of discovery/compilation/parsing/etc
- [x] refactor existing regex exercise pattern into one exercise service implementation
- [x] move exercise marker traits into their own project
- [x] kill various old code relics
- [ ] consolidate various domain model case classes (***partially done***)

### CODE REVIEW

**Comment by andyscott** [comment]
@rafaparadela @raulraja I posted this to Slack, but I figure it's worth posting here too.

The words "category" and "section" are nearly semantically interchangeable in many English usages. I'm finding it hard to keep track of which is the top level item when working on this codebase!

So... I propose we use “library” as the top level grouping, and then use either section or category under that. I'm certainly open to other names as long as it's *something* more descriptive.

**Comment by raulraja** [comment]
@andyscott Agreed, library is a better term. @rafaparadela should probably address this change in naming in the frontend stuff he is working of for Exercise Evaluation and input validation.

**Comment by raulraja** [comment]
@andyscott If you find a point where it's not broken we can split this PR in smaller ones as some other folks are gonna start touching the backend soon and I would hate for you to go through merge hell when this is done. Your call.

**Comment by andyscott** [comment]
@raulraja I went ahead and rebased it on top of the recent changes. It should be ready for a merge now but I'm out of the office today-- so if you or anyone else would like to get this in before others start working on other aspects of the code, please go ahead and merge it.

**Comment by raulraja** [comment]
@rafaparadela Can you go ahead and merge this in to `version2`?

**Comment by rafaparadela** [comment]
It works as expected. Good job @andyscott .

**Pull request merged**
