### PR TITLE
Use ExerciseType instead of Strings for type safety

### LINKED ISSUE #256: Technical Debt - Postgres Enums
We should use Meta instances to use the `ExerciseType` (UserProgress Table) case object with implicit auto-conversions to the varchar and vice versa.

### PR DESCRIPTION
**Pull request by dialelo**
- Adds a `Meta` instance so we can insert and read ExerciseType from the
  database
- Implements a reader for the JSON "exerciseType" attribute
- Modifies types coercing ExerciseType to/from String to use
  ExerciseType

Closes #256

### CODE REVIEW

**Comment by dialelo** [comment]
@raulraja @juanpedromoreno @rafaparadela please take a look!

**Comment by juanpedromoreno** [comment]
Outstanding work! LGTM.

**Comment by dialelo** [comment]
:shipit:

**Comment by juanpedromoreno** [comment]
:shipit:

**Pull request merged**
