### PR TITLE
Simplifies the exercise evaluation result

### PR DESCRIPTION
**Pull request by juanpedromoreno**
This PR is a pair programming between @raulraja and me.

Please, @andyscott @dialelo review when you have a chance. Thanks.

### CODE REVIEW

**Comment by andyscott** [comment]
@raulraja I think the ADT is the way to go. As it stands, this PR undoes some of the work yesterday that addressed specifically capturing the exceptions thrown in the eval'd method. For example, if the exercise is:
```scala
true should be(__)
```
and you enter `false`, then code will compile and run but you will still get an error that indicates otherwise.

**Comment by raulraja** [comment]
Feel free to discard the PR but we need the simplify the nested Xor now
because a bug was discovered when reporting it from the lack of proper
pattern matching on the result. I don't think it's OK to expect the call
site for this method to provide exhaustive matching for double nested Xor
Ior paths. If there is a way to express all the errors and still obtain a
single List[Ex] Xor A then that is what we want.

**Comment by andyscott** [comment]
The nesting definitely should be simplified.

**Comment by andyscott** [comment]
See preliminary work in #236.

**Comment by juanpedromoreno** [comment]
This PR is covered by https://github.com/47deg/scala-exercises/pull/236.

**Pull request closed without merging**
