### PR TITLE
Run and pass tests in ci

### PR DESCRIPTION
**Pull request by dialelo**
- Switch to old Travis infrastructure and disable forking in tests since there are [known issues](https://github.com/travis-ci/travis-ci/issues/3775) with such options in Travis CI.
- Disable `ExerciseServiceSpec` failing tests due to the overhaul of the library compiler.
- Run ScalaCheck tests with ScalaTest instead of specs2, since failures with specs2 don't make the build fail, this is likely an issue in specs2.

### CODE REVIEW

**Comment by dialelo** [comment]
Fixed a problem with a clash of jquery in the classpath, as well as another with ScalaCheck where we were generating strings with the null byte and Postgres didn't accept them. If Travis says it's ok this should be good to merge.

**Comment by rafaparadela** [comment]
Great @dialelo ! LGTM

**Comment by rafaparadela** [comment]
Let's wait for @raulraja review.

**Comment by raulraja** [comment]
LGTM

**Pull request merged**
